"""New Migration

Revision ID: 632e74428558
Revises: b8a97d3e7964
Create Date: 2024-06-25 16:26:46.054567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632e74428558'
down_revision = 'b8a97d3e7964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
