"""New Migration

Revision ID: b8a97d3e7964
Revises: ad919cf14927
Create Date: 2024-06-25 16:08:16.447721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8a97d3e7964'
down_revision = 'ad919cf14927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
